### ISSUE TITLE
Old Blog Post - 500 error

### ISSUE THREAD

**Issue by ganapathichidambaram** [weierophinney/mwop.net#33]
### Bug Report

Old Post throws error

|    Q        |   A
|------------ | ------
| Version(s)  | Latest

#### Summary

Sample non-working URL : https://mwop.net/blog/10-SSH-tips-and-tricks.html 

#### Current behavior

500 error

#### How to reproduce

Search SSH on search console and click any results or something like any older post.

#### Expected behavior

Supposed to render the page and should show the article view.

Also Readme.md for clone and setup configuration are updated then its easy for us. Sample env file or fields which is mandatory.

**Comment by weierophinney** [comment]
Try again - it appears to be reachable at this time.

> Also Readme.md for clone and setup configuration are updated then its easy for us. Sample env file or fields which is mandatory.

I provide the source code here mainly for examples (I often link to portions of my code from the Laminas slack to demonstrate ways to accomplish particular tasks), not to allow running the site yourself.
